<?php
/**
 * View class
 * responsible for viewing the data generated by the controllers
 *
 * @author Malte Bublitz
 */

namespace rahmenwerk;

class View {
	private $template_path="";
	private $template_name="";
	private $data = Array();
	private $error = Array(
		"code" => 200
	);
	public function setTemplatePath($new_path) {
		$this->template_path = $new_path;
	}
	public function setTemplateName($new_name) {
		$this->template_name = $new_name;
	}
	public function loadData($data) {
		$this->data = $data;
	}
	public function setErrorCode($code) {
		$this->error = $code;
	}
	public function sendHeaders() {
		if ($this->error["code"]!=200) {
			switch ($this->error["code"]) {
				case 403:
					header("HTTP/1.1 403 Forbidden");
					header("Status: 403 Forbidden"); // for FastCGI
					break;
				case 404:
					header("HTTP/1.1 404 Not Found");
					header("Status: 404 Not Found"); // for FastCGI
					break;
			}
		}
	}
	public function sendContent() {
		global $d;
		$d = $this->data;
		require_once($this->template_path.$this->template_name."/main.tpl.php");
	}
}

?>
